---
 - name: WebServer | Create WEB Security Group
   local_action:
     module: ec2_group
     name: "{{ item.sg_name }}"
     description: "{{ item.sg_description }}"
     region: "{{ vpc_region }}" # Change the AWS region here
     vpc_id: "{{ vpc.vpc_id }}" # vpc is the resgister name, you can also set it manually
     state: present
     rules: "{{ item.sg_rules }}"
   with_items: "{{ web_security_groups }}"
   register: web_sg

 - name: WebServer | Tag the WEB Security Group with a name
   local_action:
     module: ec2_tag
     resource: "{{ item.group_id}}"
     region: "{{ vpc_region }}"
     state: present
     tags:
       Name: "{{ vpc_name }}-{{ item.item.sg_name }}"
   with_items: "{{ web_sg.results }}"
 
 - name: WebServer | Search for Ubuntu AMI
   ec2_ami_search:
     region: "{{ vpc_region|default('us-east-1') }}"
     distro: "{{ linux_distribution }}"
     release: "{{ ubuntu_release }}"
     store: "{{ ami_store }}"
     virt: "{{ virutalization_type }}"
     arch: "{{ cpu_architecture }}"
   register: imgae_id
 
 - name: WebServer | Create the WebServer Instance(s)
   #become: yes
   #become_user: ec2-user
   local_action:
     #become: yes
     #become_method: sudo
     module: ec2
     region: "{{ vpc_region }}"
     group: "{{ web_security_groups[0].sg_name }}"
     keypair: "{{ key_name }}"
     instance_type: "{{ web_instance_type }}"
     #image: "{{ imgae_id.ami }}"
     image: ami-b63769a1
     vpc_subnet_id: "{{ item }}"
     assign_public_ip: True
     wait: True
     wait_timeout: 10000
     user_data: |
               #!/bin/sh
               sudo yum install wget unzip -y
               echo "export JAVA_HOME=~/jdk1.7.0_79" >> ~/.bashrc
               echo "export JRE_HOME=~/jdk1.7.0_79/jre" >> ~/.bashrc
               echo "export PATH=$PATH:~/jdk1.7.0_79/bin:/jdk1.7.0_79/jre/bin" >> ~/.bashrc
               cd ~
               wget http://liquidtelecom.dl.sourceforge.net/project/lportal/Liferay%20Portal/7.0.2%20GA3/liferay-ce-portal-tomcat-7.0-ga3-20160804222206210.zip
               wget --no-cookies --no-check-certificate --header "Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz"
               unzip liferay-ce-portal-tomcat-7.0-ga3-20160804222206210.zip 
               tar -xzvf jdk-8u91-linux-x64.tar.gz
               source ~/.bashrc 
               sh ~/liferay-ce-portal-7.0-ga3/tomcat-8.0.32/bin/startup.sh
               
     instance_tags:
       Name: "{{ vpc_name }}_WEB_Instance"
       Environment: "{{ ENV }}"
       Role: "{{ server_role }}"
       Application: "{{ application }}"
   with_items:
      - "{{ public_subnet_1 }}"
      - "{{ public_subnet_2 }}"
   register: web

 - name: WebServer | Set the Instances facts
   set_fact:
     instance_public_ip_1: "{{ web.results[0].instances[0].public_ip }}"
     instance_id_1: "{{ web.results[0].instances[0].id }}"
     instance_public_ip_2: "{{ web.results[1].instances[0].public_ip }}"
     instance_id_2: "{{ web.results[1].instances[0].id }}"

 - name: WebServer | Add the newly created EC2 instance(s) to the local host group (located inside the directory)
   local_action: 
     module: lineinfile 
     dest: "./hosts" 
     regexp: "{{ item }}" 
     insertafter: "[webserver]" 
     line: "{{ item }}"
   with_items:
      - "{{ instance_public_ip_1 }}"
      - "{{ instance_public_ip_2 }}" 

 - name: WebServer | Wait for SSH to come up
   local_action: 
     module: wait_for 
     host: "{{ item }}" 
     port: 22
     state: started
   with_items: 
     - "{{ instance_public_ip_1 }}"
     - "{{ instance_public_ip_2 }}" 
     
 - name: LiferayServer | Wait for 8080 to come up
   local_action: 
     module: wait_for 
     host: "{{ item }}" 
     port: 8080 
     state: started
     timeout: 600
   with_items: 
     - "{{ instance_public_ip_1 }}"
     - "{{ instance_public_ip_2 }}" 

 - name: Create SSH Group to login dynamically to EC2 Instance(s)
   add_host: 
     hostname: "{{ item }}"
     groupname: webserver
   with_items: 
     - "{{ instance_public_ip_1 }}"
     - "{{ instance_public_ip_2 }}" 
